### ISSUE TITLE
Fails on loading starbases - with fix

### ISSUE THREAD

**Issue by garygause** [PyPDX/stellaris-save-vid#1]
For my version of the savefile, the website gives an error when loading the starbases in gamestate.js.  If you run this locally, you can fix the error with the change below.

gamestate.js: line 7

change:
        this.starbases = BaseIdMapObject.loadDict(Starbase, this._data.starbases, this);

to:
        this.starbases = BaseIdMapObject.loadDict(Starbase, this._data.starbase_mgr.starbases, this);

FYI
To run locally in a simple way, just clone the repo.  cd into the directory and run:

- python 2x: 
python -m SimpleHTTPServer

python 3x: 
python -m http.server 8000

and open in browser.

**Comment by MichaelKim0407** [comment]
I haven't been using this app for a while. Is this caused by an update to Stellaris? What version are you playing?

**Comment by garygause** [comment]
v3.2.2 on steam.

-Gary

**Comment by MichaelKim0407** [comment]
Ok, thanks. Since you already figured out the problem, would you like to submit a pull request? Maybe keep compatibility in case someone's playing an older version.
